version: "3"
services:
  postgres:
    image: "postgres:13"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data

  codam-coalitions:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./.env:/app/.env
      - ./coal.db:/app/coal.db
    environment:
      - NODE_ENV=development
